### PR TITLE
Website for Fit N Life gym in Kakkanad

### PR DESCRIPTION
**Pull request by Jenin82**

### CODE REVIEW

**Comment by AswinAsok** [comment]
Do update the lorem ipsum in the end section other wise its good to go!

**Comment by Jenin82** [comment]
waiting for feedback from the client about the the contents that will replace the lorem ipsum

**Comment by AswinAsok** [comment]
Alright do updates once the the feedback has been received from the client

**Comment by AswinAsok** [comment]
@Jenin82, Do create a new PR once the required changes has been made, Closing it for the being.

**Pull request closed without merging**
